### PR TITLE
Correct small typo in Gandalf set-up documentation

### PR DESCRIPTION
**Pull request by annashipman**
There are three steps not two.

### CODE REVIEW

**Comment by fsouza** [comment]
Thank you!

**Comment by fsouza** [comment]
I think that all of this "it's a ..." is not necessary. We could go with just "In order to use Gandalf, you need to change tsuru.conf accordingly:".

This way we don't need to change the number again if we add or remove a bullet.

What do you think?

**Comment by annashipman** [comment]
Oh yes, good thinking. I'll rebase.

I can't see why Travis has failed.

**Comment by annashipman** [comment]
I've updated it as you suggested.

**Comment by fsouza** [comment]
The failure is probably from an intermittent test:

```
----------------------------------------------------------------------
FAIL: auto_scale_test.go:334: S.TestAutoScaleConfigRunRebalanceOnly

auto_scale_test.go:403:
    c.Assert(evts, check.HasLen, 1)
... obtained []docker.autoScaleEvent = []docker.autoScaleEvent(nil)
... n int = 1
OOPS: 331 passed, 1 FAILED
--- FAIL: Test (41.13s)
```

@cezarsa have you seen this failure before?

**Comment by fsouza** [comment]
@annashipman merging it, thank you!

**Pull request merged**
