### PR TITLE
start a gops agent in tsurud

### PR DESCRIPTION
**Pull request by felipeweb**
#1495

### CODE REVIEW

**Comment by andrewsmedina** [comment]
@felipeweb thank for contribute. 

tsuru uses `govendor` https://github.com/kardianos/govendor to vendorize dependencies. You should vendorize `godps` too.

If you need help let us know.

**Comment by felipeweb** [comment]
@andrewsmedina is vendorized https://github.com/felipeweb/tsuru/commit/c14de3e719c9e951f0ec957013ff2eda2ac680d4

**Comment by andrewsmedina** [comment]
@felipeweb the tests are broken because thub.com/google/gops/internal and github.com/google/gops/agent are not vendorized

you can see the tests output here: https://travis-ci.org/tsuru/tsuru/builds/177308721

**Comment by felipeweb** [comment]
@andrewsmedina  sorry my fault. all missing dependencies added here https://github.com/tsuru/tsuru/pull/1496/commits/7727822062d98e8835d54d858480731ded8d7d7f

**Comment by andrewsmedina** [comment]
@felipeweb thank you!

**Pull request merged**
