### PR TITLE
api: prevents adding units in stopped apps

### PR DESCRIPTION
**Pull request by ArxdSilva**
fixes tsuru/tsuru#1347

### CODE REVIEW

**Comment by andrestc** [comment]
Should we allow adding units *only* if all current units are started or should we allow adding units if there are some units in `starting`, `error` etc states? ping @cezarsa @ggarnier

**Comment by cezarsa** [comment]
Yeah, I think we should only prevent the addition of new units if they are with StatusStopped. Also, this logic should move to the `app` package.

**Comment by ArxdSilva** [comment]
@cezarsa that was something that kept me thinking about where it'd be best, thanks!

**Comment by ggarnier** [comment]
@cezarsa StatusStopped or StatusAsleep

**Pull request merged**
