### PR TITLE
Validate if pool exists before adding a cluster to it

### PR DESCRIPTION
**Pull request by VitorFalcao**
Fix issue #1696

### CODE REVIEW

**Comment by VitorFalcao** [comment]
@andrestc Sure! Working on it.

**Comment by VitorFalcao** [comment]
@andrestc Should I also validate if the pool exists in the method `updateCluster` in `api/cluster`? And before the `createCluster` method there is a comment section specifying the possible return codes and their meanings. Should I add 404 to that list?

**Comment by andrestc** [comment]
@VitorFalcao yes, i think so.

**Comment by VitorFalcao** [comment]
@andrestc The `updateCluster` method of `api/cluster` already has a 404 code specified for when the cluster does not exist. Is there any problem in returning the same code for when a pool does not exist?

**Comment by andrestc** [comment]
I think we could return 400 in this case.

Em 16 de out de 2017 19:23, "Nope" <notifications@github.com> escreveu:

**Comment by VitorFalcao** [comment]
@andrestc The method already uses that code for `Invalid data`

**Comment by andrestc** [comment]
Thats ok, just make sure to add a message describing the error cause in the
body of the response

Em 16 de out de 2017 19:39, "Nope" <notifications@github.com> escreveu:

**Comment by ggarnier** [comment]
@VitorFalcao thank you!

**Pull request merged**
