### PR TITLE
validation: testing prefix+email.com case on ValidateEmail

### PR DESCRIPTION
**Pull request by guilhermebruzzi**
Proving the issue https://github.com/tsuru/tsuru/issues/1442 isn't a email validation's problem by improving email validation's tests.

### CODE REVIEW

**Comment by guilhermebruzzi** [comment]
P.S.: I was only able to run tsuru server and test this PR after this commit (not present on this PR): https://github.com/tsuru/tsuru/commit/5c7a955d83ff4e9d1c87fd1d29f847f4bcf4272d

**Comment by andrewsmedina** [comment]
@guilhermebruzzi thank you!

**Comment by guilhermebruzzi** [comment]
@andrewsmedina :D

**Comment by fsouza** [comment]
fastparrot

**Pull request merged**
