### PR TITLE
cmd/tsuru: move all client config files to .tsuru

### LINKED ISSUE #775: cmd/tsuru: move all client config files to .tsuru
currently tsuru client creates a directory `.tsuru` to install the cli plugins. The client should uses this directory for the config files too. The files are:

* .tsuru_token
* .tsuru_target
* .tsuru_targets

### PR DESCRIPTION
**Pull request by ggarnier**
Move client config files to `$HOME/.tsuru` folder, and remove `tsuru_` prefix from the file names. This fixes #775.

I just don't know how you should do the migration from the old to the new files.

### CODE REVIEW

**Comment by ggarnier** [comment]
@andrewsmedina can you help me understand the build error?

**Comment by andrewsmedina** [comment]
@ggarnier seems like is something with travis. I restarted the build and all tests pass now. :)

It is necessary to update the tsuru/cmd package in https://github.com/tsuru/tsuru-client, https://github.com/tsuru/tsuru-admin and https://github.com/tsuru/crane to reflect these changes in the clients.

**Comment by andrewsmedina** [comment]
@ggarnier thank you!

**Comment by ggarnier** [comment]
@andrewsmedina ok, I'll do it!

**Comment by andrewsmedina** [comment]
@ggarnier if you need help let us know

**Pull request merged**
